import 'tailwindcss/tailwind.css';
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "IA App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
